name: Run Autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Select a file to run
        required: true
        type: choice
        default: all
        options:
        - smoke
        - regression
        - all

jobs:
  run-tests:
    runs-on: Windows 11
    name: Tests
    steps:
      - name: Copy source code
        uses: actions/checkout@v4
      - name: Set up Python env
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: pip install requirements.txt
      - name: Run tests
        run: pytest -v
        
      
