name: Run Autotests

on:
  workflow_dispatch:
    inputs:
      description: Select a file to run
      required: true
      type: choice
      default: all
      options:
      - smoke
      - regression
      - all
